language: node_js
node_js: 
  - "0.10"
before_script:
  - npm install
  - bower install
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: ./node_modules/karma/bin/karma start --single-run
after_failure: find . -type f -path "~/mapsandtexts" -name "npm-debug.log" -print -exec cat {} \;
